// Shared type definitions for InterviewPrep AI.

export type QuestionType = 'mcq' | 'true_false'

/**
 * One interview question generated by the AI.
 * MCQ questions have exactly 4 options; true/false questions have exactly 2.
 * `correctAnswer` is the index of the correct option.
 */
export interface QuizQuestion {
  id: number
  type: QuestionType
  question: string
  options: string[]
  correctAnswer: number
}

/** Structured JSON returned by the AI for a job description analysis. */
export interface ExtractSkillsAndQuizResponse {
  skills: string[]
  questions: QuizQuestion[]
}

export interface QuizResult {
  score: number
  totalQuestions: number
  correctAnswers: number
  completedAt: string
}
