// Shared type definitions for RolePrep AI.

/** One multiple-choice interview question generated by the AI. */
export interface QuizQuestion {
  question: string
  options: string[]
  correctAnswer: string
  explanation: string
}

/** Structured JSON returned by the AI for a job description analysis. */
export interface ExtractSkillsAndQuizResponse {
  skills: string[]
  questions: QuizQuestion[]
}

export interface QuizResult {
  score: number
  totalQuestions: number
  correctAnswers: number
  completedAt: string
}
